/*
 * GPIO_configure.c

 *
 *  Created on: Oct 12, 2019
 *      Author: AhmedShawky
 */
#include "std_types.h"
#include "GPIO_Int.H"
u8 GPIODR2R_Val[PORTS_NUMBER]={0xff,0xff,0xff,0xff,0xff,0xff};
u8 GPIODR4R_Val[PORTS_NUMBER]={0x00,0x00,0x00,0x00,0x00,0x00};
u8 GPIODR8R_Val[PORTS_NUMBER]={0x00,0x00,0x00,0x00,0x00,0x00};
u8 GPIOODR_Val[PORTS_NUMBER]={0x00,0x00,0x00,0x00,0x00,0x00};

//NOTE THAT THE PUR IS EXECUTED AFTER THE PDR SO TAKE CARE OF CONFLICTION
u8 GPIOPUR_Val[PORTS_NUMBER]={0x00,0x00,0x00,0x00,0x00,0x00};
u8 GPIOPDR_Val[PORTS_NUMBER]={0xE0,0x00,0x00,0x00,0x00,0x00};
u8 GPIODEN_Val[PORTS_NUMBER]={0xff,0xff,0xff,0xff,0x00,0xff};





//THIS SECTION IS FOR INTERRUPT CONFIGURATION, EACH ARRAY INDEX CORRESPONDS TO A PORT'S GPIOIS REGISTER VALUE
//IF A BIT IN THE GPIOIS IS SET,THEN THE INTERRUPT DETECTS LEVELS, IF A BIT IS CLEARED THEN IT DETECTS EDGES

u8 GPIOIS_Val[PORTS_NUMBER]={0x00,0x00,0x00,0x00,0x00,0x00};

//When the corresponding bit in the GPIO Interrupt Sense (GPIOIS) register is set to detect edges, setting a bit in the
//GPIOIBE register configures the corresponding pin to detect both rising and falling edges, regardless
//of the corresponding bit in the GPIO Interrupt Event (GPIOIEV) register. Clearing
//a bit configures the pin to be controlled by the GPIOIEV register.

u8 GPIOIBE_Val[PORTS_NUMBER]={0xE0,0x00,0x00,0x00,0x00,0x00};

//Setting a bit in the GPIOIEV register configures the corresponding pin to detect rising edges or high levels,
//depending on the corresponding bit value in the GPIO Interrupt Sense (GPIOIS) register.
//Clearing a bit configures the pin to detect falling edges or low levels, depending on the corresponding bit value in the GPIOIS

u8 GPIOIEV_Val[PORTS_NUMBER]={0xff,0xff,0xff,0xff,0xff,0xff};


//The GPIOIM register is the interrupt mask register. Setting a bit in the GPIOIM register allows
//interrupts that are generated by the corresponding pin to be sent to the interrupt controller on the
//combined interrupt signal. Clearing a bit prevents an interrupt on the corresponding pin from being
//sent to the interrupt controller. All bits are cleared by a reset.
//HERE WE ARE GOING TO SUBSTITUTE THE GPIOIM CONFIGURATION WITH THE GPIO_PIN_INT CONFIGURATION FOR EACH PIN INDIVIDUALLY.
